/**
 * Data module: sensitive file/path probes used by probes.ts active checks.
 * Keeping this separate reduces probes.ts from ~1500 lines to ~650.
 */

import type { ScanVulnerability } from "./scanner";

export interface SensitivePath {
  path: string;
  name: string;
  severity: ScanVulnerability["severity"];
  cweId: string;
  cvssScore?: number;
  category: string;
  description: string;
  solution: string;
  validate: (body: string, contentType: string) => boolean;
}

export const SENSITIVE_PATHS: SensitivePath[] = [
  // ── Version control ──────────────────────────────────────────────────────
  {
    path: "/.git/HEAD",
    name: "Git Repository Exposed",
    severity: "critical", cweId: "CWE-538", cvssScore: 9.8,
    category: "Source Code Exposure",
    description: "The .git directory is publicly accessible. Attackers can reconstruct your entire source code history—including deleted files, credentials ever committed, and all branches—using tools like git-dumper.",
    solution: "Block /.git at the web server: Nginx: `location ~ /\\.git { deny all; return 404; }` Apache: `<Directory .git> Deny from all </Directory>`. Never deploy VCS directories to a public web root.",
    validate: (body) => /^ref: refs\/heads\/\S+/.test(body.trim()) || /^[0-9a-f]{40}$/m.test(body.trim()),
  },
  {
    path: "/.git/config",
    name: "Git Config Exposed",
    severity: "high", cweId: "CWE-538", cvssScore: 7.5,
    category: "Source Code Exposure",
    description: "The Git configuration file is publicly accessible, revealing remote repository URLs, branch names, and any credentials stored via git-credential helpers.",
    solution: "Block all access to .git at the web server level.",
    validate: (body) => /\[core\]|\[remote\s|repositoryformatversion/.test(body),
  },
  {
    path: "/.svn/entries",
    name: "SVN Repository Exposed",
    severity: "high", cweId: "CWE-538", cvssScore: 7.5,
    category: "Source Code Exposure",
    description: "A Subversion (.svn) metadata directory is publicly accessible, potentially exposing the full source code tree.",
    solution: "Block .svn directories: `location ~ /\\.svn { deny all; }`",
    validate: (body) => /^\d+\n/.test(body) || /dir\n/.test(body.slice(0, 100)),
  },
  {
    path: "/.hg/requires",
    name: "Mercurial Repository Exposed",
    severity: "high", cweId: "CWE-538", cvssScore: 7.5,
    category: "Source Code Exposure",
    description: "A Mercurial (.hg) repository directory is publicly accessible.",
    solution: "Block .hg directories at the web server level.",
    validate: (body) => /dotencode|fncache|revlogv/.test(body),
  },

  // ── Environment / credentials ────────────────────────────────────────────
  {
    path: "/.env",
    name: "Environment File Exposed (.env)",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "A .env file is publicly accessible. This file typically contains database passwords, API keys, JWT secrets, and third-party tokens in plaintext. Attackers can immediately compromise every connected service.",
    solution: "Rotate ALL credentials in the file immediately. Block .env* files: `location ~ /\\.env { deny all; }`. Never place .env files in the web root.",
    // Require at least one KEY=value line AND no HTML content regardless of
    // content-type — servers that return soft-404 HTML pages as text/plain were
    // previously passing this check due to the !ct.includes("text/html") short-circuit.
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.local",
    name: "Environment File Exposed (.env.local)",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: ".env.local is publicly accessible. This override file often contains developer or staging credentials.",
    solution: "Block all .env* files at the web server and rotate any exposed credentials.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.production",
    name: "Production Environment File Exposed (.env.production)",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "The production .env file is publicly accessible, exposing live database credentials, payment keys, and all production secrets.",
    solution: "Block all .env* files immediately and rotate all exposed production credentials.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.backup",
    name: "Backup Environment File Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.1,
    category: "Credential Exposure",
    description: "A backup of the environment config is publicly accessible.",
    solution: "Delete .env backups from the server. Block all .env* files.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.staging",
    name: "Staging Environment File Exposed",
    severity: "high", cweId: "CWE-312", cvssScore: 8.2,
    category: "Credential Exposure",
    description: "Staging environment configuration is publicly accessible, which often shares similar credentials to production.",
    solution: "Block all .env* files at the web server.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },

  // ── PHP / CMS configs ────────────────────────────────────────────────────
  {
    path: "/wp-config.php",
    name: "WordPress Config File Exposed (wp-config.php)",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "WordPress configuration is accessible as source code (PHP not executing). This exposes the database host, name, username, password, table prefix, and all WordPress secret keys.",
    solution: "Ensure PHP is correctly configured to execute .php files. Move wp-config.php one level above the web root as an additional safeguard.",
    validate: (body) => /DB_NAME|DB_PASSWORD|DB_USER|table_prefix|AUTH_KEY/.test(body),
  },
  {
    path: "/phpinfo.php",
    name: "PHP Info Page Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "A phpinfo() page is accessible. This reveals PHP version, all loaded modules, server paths, environment variables (including $_ENV secrets), and configuration values—a complete reconnaissance package for attackers.",
    solution: "Delete phpinfo.php from production. Never deploy debug scripts to production servers.",
    validate: (body) => /phpinfo\(\)|PHP Version|<title>phpinfo\(\)/i.test(body),
  },
  {
    path: "/info.php",
    name: "PHP Info Page Exposed (info.php)",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "A PHP info page is accessible, disclosing detailed server and environment configuration.",
    solution: "Delete info.php from production immediately.",
    validate: (body) => /phpinfo\(\)|PHP Version|PHP Variables/i.test(body),
  },
  {
    path: "/config.php",
    name: "PHP Config File Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.1,
    category: "Credential Exposure",
    description: "A PHP configuration file is accessible as source code, potentially exposing database credentials and application secrets.",
    solution: "Ensure PHP processes .php files. Block direct web access to config files.",
    validate: (body) => /\$(?:db_|database|password|pass|secret|key|host)/i.test(body),
  },
  {
    path: "/configuration.php",
    name: "Joomla Configuration Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "The Joomla configuration file is accessible as source, exposing database credentials and secret keys.",
    solution: "Ensure PHP is executing .php files. Verify web server configuration for the Joomla directory.",
    validate: (body) => /JConfig|db_name|db_password|db_prefix|\$password/i.test(body),
  },
  {
    path: "/settings.php",
    name: "Drupal Settings File Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "The Drupal settings.php file is accessible as source code, exposing database credentials and hash salt.",
    solution: "Ensure PHP is configured to execute .php files, not serve them raw.",
    validate: (body) => /\$databases|\$db_url|hash_salt|drupal_hash_salt/i.test(body),
  },

  // ── Database backups ─────────────────────────────────────────────────────
  {
    path: "/backup.sql",
    name: "Database Backup Exposed",
    severity: "critical", cweId: "CWE-552", cvssScore: 9.8,
    category: "Data Exposure",
    description: "A SQL database backup is publicly downloadable. An attacker can download your entire database including user credentials, personal data, and all application records.",
    solution: "Remove all database dumps from the web root immediately. Store backups encrypted in a private, non-web-accessible location.",
    validate: (body) => /CREATE TABLE|INSERT INTO|DROP TABLE|-- MySQL dump|-- PostgreSQL database dump/i.test(body.slice(0, 3000)),
  },
  {
    path: "/dump.sql",
    name: "Database Dump Exposed",
    severity: "critical", cweId: "CWE-552", cvssScore: 9.8,
    category: "Data Exposure",
    description: "A database dump is publicly accessible.",
    solution: "Remove dump.sql from the web root.",
    validate: (body) => /CREATE TABLE|INSERT INTO|DROP TABLE|-- (MySQL|Dump|PostgreSQL)/i.test(body.slice(0, 3000)),
  },
  {
    path: "/db.sql",
    name: "Database File Exposed",
    severity: "critical", cweId: "CWE-552", cvssScore: 9.8,
    category: "Data Exposure",
    description: "A database file is publicly accessible.",
    solution: "Remove db.sql from the web root.",
    validate: (body) => /CREATE TABLE|INSERT INTO|DROP TABLE|PRAGMA/i.test(body.slice(0, 3000)),
  },
  {
    path: "/database.sql",
    name: "Database Export Exposed",
    severity: "critical", cweId: "CWE-552", cvssScore: 9.8,
    category: "Data Exposure",
    description: "A database export file is publicly accessible.",
    solution: "Remove database.sql from the web root.",
    validate: (body) => /CREATE TABLE|INSERT INTO|DROP TABLE/i.test(body.slice(0, 3000)),
  },
  {
    path: "/backup.zip",
    name: "Backup Archive Exposed",
    severity: "critical", cweId: "CWE-552", cvssScore: 9.1,
    category: "Source Code Exposure",
    description: "A backup archive is publicly downloadable. This likely contains source code, configuration files with credentials, and database exports.",
    solution: "Remove all backup files from the web root. Store backups in a private, access-controlled location.",
    validate: (body, ct) => ct.includes("zip") || ct.includes("octet-stream") || body.slice(0, 2) === "PK",
  },
  {
    path: "/backup.tar.gz",
    name: "Backup Archive Exposed (.tar.gz)",
    severity: "critical", cweId: "CWE-552", cvssScore: 9.1,
    category: "Source Code Exposure",
    description: "A tar.gz backup archive is publicly downloadable.",
    solution: "Remove backup archives from the web root.",
    validate: (_, ct) => ct.includes("gzip") || ct.includes("octet-stream") || ct.includes("tar"),
  },

  // ── API documentation ─────────────────────────────────────────────────────
  {
    path: "/swagger.json",
    name: "API Documentation Exposed (Swagger)",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "Swagger/OpenAPI documentation is publicly accessible without authentication. This gives attackers a complete blueprint of every API endpoint, required parameters, authentication schemes, and data models.",
    solution: "Require authentication to access API docs in production. Add middleware to protect /swagger.json and /swagger-ui.html, or serve docs only on internal network.",
    validate: (body) => /"swagger"|"openapi"/.test(body.slice(0, 500)),
  },
  {
    path: "/openapi.json",
    name: "API Documentation Exposed (OpenAPI)",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "OpenAPI documentation is publicly accessible, providing a complete map of your API surface.",
    solution: "Restrict API docs to authenticated users or internal network access.",
    validate: (body) => /"openapi"|"swagger"/.test(body.slice(0, 500)),
  },
  {
    path: "/swagger-ui.html",
    name: "Swagger UI Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "Swagger UI is publicly accessible, allowing anyone to browse, test, and interact with your API directly from their browser.",
    solution: "Require authentication to access Swagger UI in production environments.",
    validate: (body) => /swagger-ui|SwaggerUI/i.test(body),
  },
  {
    path: "/api-docs",
    name: "API Documentation Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "API documentation is publicly accessible.",
    solution: "Restrict API documentation to authenticated users.",
    validate: (body) => /"swagger"|"openapi"|"paths"/.test(body.slice(0, 1000)),
  },
  {
    path: "/graphql",
    name: "GraphQL Introspection Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "A GraphQL endpoint appears accessible. If introspection is enabled, attackers can enumerate your entire schema including all queries, mutations, types, and fields.",
    solution: "Disable GraphQL introspection in production environments. Add depth limiting and query complexity analysis to prevent abuse.",
    validate: (body) => /\"__schema\"|\"__type\"|graphql|GraphQL/i.test(body),
  },

  // ── Spring Boot Actuator ─────────────────────────────────────────────────
  {
    path: "/actuator/env",
    name: "Spring Boot Actuator /env Exposed",
    severity: "critical", cweId: "CWE-200", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "Spring Boot Actuator's /env endpoint is publicly accessible. This dumps ALL environment variables, configuration properties, and system properties—including database passwords, API keys, and every secret your application uses.",
    solution: "Secure all Actuator endpoints: `management.endpoints.web.exposure.include=health` only. Restrict remaining endpoints behind authentication or to localhost only.",
    validate: (body) => /"activeProfiles"|"propertySources"|"systemEnvironment"/.test(body.slice(0, 1000)),
  },
  {
    path: "/actuator/configprops",
    name: "Spring Boot Config Properties Exposed",
    severity: "critical", cweId: "CWE-200", cvssScore: 9.1,
    category: "Credential Exposure",
    description: "Spring Boot Actuator's configprops endpoint exposes all configuration properties including sensitive values.",
    solution: "Never expose configprops in production. Restrict all Actuator endpoints.",
    validate: (body) => /"contexts"|"beans"|"properties"/.test(body.slice(0, 500)),
  },
  {
    path: "/actuator/beans",
    name: "Spring Boot Beans Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "Spring Boot Actuator's beans endpoint reveals the full application component structure and wiring.",
    solution: "Restrict all Actuator endpoints to internal network access only.",
    validate: (body) => /"beans"|"applicationContextId"/.test(body.slice(0, 500)),
  },

  // ── Config files ─────────────────────────────────────────────────────────
  {
    path: "/config.json",
    name: "Configuration File Exposed (config.json)",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "A configuration JSON file is publicly accessible, potentially containing connection strings, API keys, or internal endpoint URLs.",
    solution: "Remove config.json from the web root. Use environment variables for configuration, never static files.",
    validate: (body, ct) => (ct.includes("json") || body.trim().startsWith("{")) && !ct.includes("text/html"),
  },
  {
    path: "/Dockerfile",
    name: "Dockerfile Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "The application's Dockerfile is publicly accessible, revealing the exact base image, build steps, exposed ports, and potentially build-time secrets passed as ARGs.",
    solution: "Remove Dockerfile from the web root. Only deploy built application artifacts.",
    validate: (body) => /^FROM\s+\S+/m.test(body),
  },
  {
    path: "/docker-compose.yml",
    name: "Docker Compose Config Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "docker-compose.yml is publicly accessible, revealing service configurations, port mappings, volume mounts, and potentially hardcoded environment variables with credentials.",
    solution: "Remove docker-compose.yml from the web root.",
    validate: (body) => /^services:|^version:/.test(body),
  },
  {
    path: "/package.json",
    name: "Package Manifest Exposed (package.json)",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "package.json is publicly accessible, revealing the full dependency tree and exact package versions. Attackers can identify dependencies with known CVEs and target your specific stack.",
    solution: "Block access to package.json from the web server. Ensure build artifacts are not deployed to the web root.",
    validate: (body, ct) => (ct.includes("json") || body.trim().startsWith("{")) && /"dependencies"|"scripts"|"name"/.test(body),
  },
  {
    path: "/web.config",
    name: "IIS Web Configuration Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "IIS web.config is publicly accessible. This may contain connection strings, authentication settings, and application configuration including potential credentials.",
    solution: "IIS normally blocks web.config access. Audit your IIS configuration to ensure this default protection is active.",
    validate: (body) => /<configuration>|<connectionStrings>|<appSettings>/i.test(body),
  },

  // ── Framework-specific ───────────────────────────────────────────────────
  {
    path: "/config/database.yml",
    name: "Rails Database Config Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "The Rails database.yml file is accessible, exposing database adapter, host, name, username, and password for all environments (development, test, production).",
    solution: "Block web access to the config directory. Use `DATABASE_URL` environment variable instead of hardcoding credentials in database.yml.",
    validate: (body) => /adapter:|database:|username:|password:|host:/i.test(body),
  },
  {
    path: "/config/secrets.yml",
    name: "Rails Secrets File Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "Rails secrets.yml is accessible, exposing secret_key_base and any other application secrets for all environments.",
    solution: "Block access to the config directory. Migrate to Rails encrypted credentials (`bin/rails credentials:edit`).",
    validate: (body) => /secret_key_base|development:|production:/i.test(body),
  },
  {
    path: "/local_settings.py",
    name: "Django Local Settings Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.1,
    category: "Credential Exposure",
    description: "A Django local settings file is accessible, likely containing SECRET_KEY, database credentials, and DEBUG=True.",
    solution: "Block .py files via web server rules. Never store settings files in a publicly accessible directory.",
    validate: (body) => /SECRET_KEY|DATABASES|DEBUG\s*=/.test(body),
  },

  // ── Logs ─────────────────────────────────────────────────────────────────
  {
    path: "/storage/logs/laravel.log",
    name: "Laravel Log File Exposed",
    severity: "high", cweId: "CWE-532", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "The Laravel application log is publicly accessible. Log files contain exception stack traces with full file paths, SQL queries (including parameters), request data, and sometimes inadvertently logged credentials.",
    solution: "Ensure Laravel's /storage directory is not inside or accessible from the web root. The standard Laravel setup places it correctly — verify your deployment hasn't accidentally moved it.",
    validate: (body) => /\[\d{4}-\d{2}-\d{2}.*\].*(?:INFO|ERROR|DEBUG|WARNING)/i.test(body.slice(0, 3000)),
  },
  {
    path: "/debug.log",
    name: "Debug Log File Exposed",
    severity: "medium", cweId: "CWE-532", cvssScore: 6.5,
    category: "Information Disclosure",
    description: "A debug log is publicly accessible. Logs can contain sensitive request data, stack traces, and application internals.",
    solution: "Store logs outside the web root. Block .log files: `location ~ \\.log$ { deny all; }`",
    validate: (body) => body.length > 200 && /error|warn|debug|exception|trace/i.test(body.slice(0, 3000)),
  },

  // ── Other ────────────────────────────────────────────────────────────────
  {
    path: "/.gitignore",
    name: ".gitignore Exposes Sensitive Path Names",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: ".gitignore is publicly accessible. While not directly exploitable, it reveals the names of sensitive files on the server (e.g., '*.key', 'secrets/', 'credentials.json') that exist but aren't tracked in Git, giving attackers a targeted list of files to probe.",
    solution: "Consider blocking .gitignore at the web server to avoid disclosing the sensitive file structure.",
    // SPA catch-all returns text/html — a real .gitignore is plain text
    validate: (body, ct) => !ct.includes("text/html") && (body.includes(".env") || body.includes("secret") || body.includes("*.key") || body.length > 100),
  },
  {
    path: "/server-status",
    name: "Apache Server Status Page Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "Apache's server-status page is publicly accessible, revealing real-time request data including request URIs being processed (which may contain tokens in URLs), active connections, server version, and performance metrics.",
    solution: "Restrict server-status to localhost only: `<Location /server-status> Require local </Location>`",
    validate: (body) => /Apache Server Status|requests currently being processed/i.test(body),
  },
  {
    path: "/.DS_Store",
    name: "macOS .DS_Store File Exposed",
    severity: "low", cweId: "CWE-200",
    category: "Information Disclosure",
    description: ".DS_Store files contain macOS Finder directory metadata including file names and layouts. Tools like ds_store_exp can enumerate the complete directory structure without needing directory listing enabled.",
    solution: "Add .DS_Store to .gitignore to prevent deployment. Block access: `location = /.DS_Store { deny all; }`. Clean any existing .DS_Store files from your server.",
    validate: (_, ct) => ct.includes("octet-stream") || ct.includes("x-ds"),
  },
  {
    path: "/crossdomain.xml",
    name: "Permissive crossdomain.xml Policy",
    severity: "medium", cweId: "CWE-942", cvssScore: 6.5,
    category: "CORS Misconfiguration",
    description: "A Flash/Silverlight cross-domain policy file exists. If it allows access from all domains (*), legacy Flash or PDF plugins can make credentialed cross-origin requests to your application.",
    solution: "Remove crossdomain.xml if Flash is not used. If needed, restrict to specific domains instead of using wildcards.",
    validate: (body) => /<cross-domain-policy|allow-access-from domain/i.test(body),
  },

  // ── Additional .env variants ──────────────────────────────────────────────
  {
    path: "/.env.development",
    name: "Development Environment File Exposed (.env.development)",
    severity: "high", cweId: "CWE-312", cvssScore: 7.5,
    category: "Credential Exposure",
    description: "A development .env file is publicly accessible, potentially containing database credentials, API keys, and OAuth secrets used in development — which are often reused in staging or production.",
    solution: "Block all .env* files at the web server. Nginx: `location ~ /\\.env { deny all; }`. Never deploy .env files to the web root.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.dev",
    name: "Dev Environment File Exposed (.env.dev)",
    severity: "high", cweId: "CWE-312", cvssScore: 7.5,
    category: "Credential Exposure",
    description: "A .env.dev file is publicly accessible, potentially containing developer credentials and service keys.",
    solution: "Block all .env* files at the web server and remove them from the web root.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.development.local",
    name: "Local Development Overrides Exposed (.env.development.local)",
    severity: "high", cweId: "CWE-312", cvssScore: 7.5,
    category: "Credential Exposure",
    description: ".env.development.local is gitignored by default and contains developer-specific overrides, frequently with real third-party API credentials and database passwords.",
    solution: "Block all .env* files at the web server. This file should never be deployed.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },
  {
    path: "/.env.test",
    name: "Test Environment File Exposed (.env.test)",
    severity: "medium", cweId: "CWE-312", cvssScore: 5.3,
    category: "Credential Exposure",
    description: "A test .env file is accessible. Test environments frequently share credentials with staging or contain real third-party API keys for integration tests.",
    solution: "Block all .env* files at the web server.",
    validate: (body) => !/<html|<!DOCTYPE/i.test(body.slice(0, 200)) && /^[A-Za-z_]\w*\s*=.+/m.test(body),
  },

  // ── CI/CD pipeline configurations ─────────────────────────────────────────
  {
    path: "/.travis.yml",
    name: "Travis CI Configuration Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: ".travis.yml is publicly accessible. CI configuration files reveal deployment scripts, environment variable names (and sometimes values), server addresses, and the complete build and deployment pipeline. Attackers use this to plan targeted attacks on your infrastructure.",
    solution: "Block CI config files at the web server or ensure they are not placed in the web root. Never hardcode secrets in CI configs — use the CI provider's encrypted secrets/variables feature.",
    // YAML CI files must not return text/html — that's an SPA catch-all serving index.html
    validate: (body, ct) => !ct.includes("text/html") && /language:|script:|deploy:|env:|install:/i.test(body),
  },
  {
    path: "/.circleci/config.yml",
    name: "CircleCI Configuration Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "A CircleCI configuration file is publicly accessible, revealing the full build, test, and deployment pipeline including any environment variable references.",
    solution: "Block the .circleci directory at the web server. Store all secrets in CircleCI's project environment variables, not in the config file.",
    validate: (body, ct) => !ct.includes("text/html") && /version:|jobs:|steps:|workflows:|orbs:/i.test(body),
  },
  {
    path: "/Jenkinsfile",
    name: "Jenkinsfile CI/CD Configuration Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "A Jenkinsfile is publicly accessible. Jenkins pipeline scripts often contain deployment targets, server addresses, credential references, and the complete build and release process.",
    solution: "Block Jenkinsfile at the web server. Use Jenkins credentials store for all secrets, never inline them in the Jenkinsfile.",
    validate: (body, ct) => !ct.includes("text/html") && /pipeline|stage|steps|agent|environment|credentials/i.test(body),
  },
  {
    path: "/.gitlab-ci.yml",
    name: "GitLab CI/CD Configuration Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: ".gitlab-ci.yml is publicly accessible, revealing build stages, deployment scripts, Docker image references, and environment variable names used in the pipeline.",
    solution: "Block .gitlab-ci.yml at the web server. All secrets should use GitLab CI/CD variables, not inline values.",
    // SPA apps return text/html for every route — only flag when genuine YAML content is returned
    validate: (body, ct) => !ct.includes("text/html") && /stages:|script:|deploy:|image:|variables:/i.test(body),
  },
  {
    path: "/.drone.yml",
    name: "Drone CI Configuration Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "A Drone CI configuration file is publicly accessible, revealing pipeline steps and deployment configuration.",
    solution: "Block CI config files at the web server.",
    validate: (body, ct) => !ct.includes("text/html") && /kind:|steps:|name:|image:|commands:/i.test(body),
  },

  // ── Dependency lockfiles ───────────────────────────────────────────────────
  {
    path: "/yarn.lock",
    name: "yarn.lock Dependency Lockfile Exposed",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "yarn.lock is publicly accessible, revealing the exact version of every package in the dependency tree. Attackers cross-reference these versions against CVE databases to identify exploitable packages with precision, skipping the fingerprinting step entirely.",
    solution: "Block lockfiles at the web server. They should not be placed in the web root.",
    validate: (body) => /^# yarn lockfile|^# This file is generated/m.test(body) || (/resolved "https:\/\/registry/m.test(body) && body.length > 200),
  },
  {
    path: "/package-lock.json",
    name: "npm package-lock.json Exposed",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "package-lock.json is accessible, providing the complete resolved dependency tree with exact versions. This is a precision CVE-targeting blueprint.",
    solution: "Block lockfiles at the web server.",
    validate: (body, ct) => (ct.includes("json") || body.trim().startsWith("{")) && /"lockfileVersion"|"packages"|"dependencies"/.test(body),
  },
  {
    path: "/composer.lock",
    name: "PHP composer.lock Exposed",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "composer.lock is accessible, revealing all PHP package versions in use. Attackers use this to target known vulnerabilities in specific package versions.",
    solution: "Block composer.lock at the web server.",
    validate: (body) => /"content-hash"|"packages"|"platform"/i.test(body),
  },
  {
    path: "/Gemfile.lock",
    name: "Ruby Gemfile.lock Exposed",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "Gemfile.lock is publicly accessible, exposing all Ruby gem versions and dependency sources.",
    solution: "Block Gemfile.lock at the web server.",
    validate: (body) => /GEM\s+remote:|BUNDLED WITH|PLATFORMS/m.test(body),
  },
  {
    path: "/Pipfile.lock",
    name: "Python Pipfile.lock Exposed",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "Pipfile.lock is accessible, revealing all Python package versions. Useful for identifying vulnerable dependencies.",
    solution: "Block Pipfile.lock at the web server.",
    validate: (body) => /"_meta"|"default"|"develop"/.test(body) && /"version":/.test(body),
  },
  {
    path: "/requirements.txt",
    name: "Python requirements.txt Exposed",
    severity: "info", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "requirements.txt is publicly accessible, listing all Python dependencies and their pinned versions.",
    solution: "Block requirements.txt at the web server.",
    validate: (body) => /^[a-zA-Z][\w.-]*(==|>=|<=|~=|!=|>|<)\d/m.test(body) || (/^[a-zA-Z][\w.-]+$/m.test(body) && body.split("\n").length > 3),
  },

  // ── Cloud / infrastructure secrets ────────────────────────────────────────
  {
    path: "/terraform.tfstate",
    name: "Terraform State File Exposed — Infrastructure Secrets",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "A Terraform state file is publicly accessible. Terraform state files contain a complete inventory of your cloud infrastructure in plaintext, including resource IDs, database connection strings, API keys, access tokens, private IPs, and any secrets passed as Terraform variables or outputs. This is one of the most sensitive files in any infrastructure.",
    solution: "Remove terraform.tfstate from the web server immediately. Store Terraform state in a remote backend with encryption and access controls (Terraform Cloud, S3 with SSE, GCS). Never commit state files to repositories or deploy them to web servers.",
    validate: (body) => /"terraform_version"|"resources"|"outputs"/.test(body.slice(0, 2000)),
  },
  {
    path: "/.aws/credentials",
    name: "AWS Credentials File Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "An AWS credentials file is publicly accessible. This file contains AWS Access Key IDs and Secret Access Keys in plaintext, granting API-level access to all AWS services the associated user or role can access.",
    solution: "Remove .aws/credentials from the web server immediately. Rotate all exposed credentials in the AWS IAM console. Use IAM roles for EC2/Lambda instead of static credentials files.",
    validate: (body) => /\[default\]|aws_access_key_id|aws_secret_access_key/i.test(body),
  },
  {
    path: "/.kube/config",
    name: "Kubernetes Config File Exposed — Cluster Credentials",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "A Kubernetes kubeconfig file is publicly accessible. This file contains cluster API server addresses, client certificates or tokens, and namespace context — providing full kubectl access to the Kubernetes cluster.",
    solution: "Remove .kube/config from the web server immediately. Rotate all cluster credentials. Never deploy kubeconfig files to web servers.",
    validate: (body) => /apiVersion:|clusters:|users:|contexts:|kind: Config/i.test(body),
  },
  {
    path: "/id_rsa",
    name: "SSH Private Key Exposed (id_rsa)",
    severity: "critical", cweId: "CWE-312", cvssScore: 10.0,
    category: "Credential Exposure",
    description: "An SSH private key file is publicly accessible. Anyone who downloads this file can authenticate as the key's owner to any server that has the corresponding public key authorized. This typically grants root or admin shell access.",
    solution: "Remove id_rsa from the web server immediately and consider it completely compromised. Generate a new key pair, deploy the new public key to all servers, and revoke the old public key from all authorized_keys files.",
    validate: (body) => /-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/.test(body),
  },
  {
    path: "/.ssh/id_rsa",
    name: "SSH Private Key Exposed (.ssh/id_rsa)",
    severity: "critical", cweId: "CWE-312", cvssScore: 10.0,
    category: "Credential Exposure",
    description: "An SSH private key is publicly accessible at .ssh/id_rsa. Anyone downloading this file can authenticate as the key owner to all servers that trust this key.",
    solution: "Remove the key from the web server, revoke it from all authorized_keys files, and generate a new key pair.",
    validate: (body) => /-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----/.test(body),
  },
  {
    path: "/.bash_history",
    name: "Bash History File Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: ".bash_history is publicly accessible. Shell history files contain previously executed commands including curl requests with auth tokens, database connection strings typed directly, passwords passed as command-line arguments, and internal server addresses.",
    solution: "Remove .bash_history from the web root. Block dotfiles at the web server: `location ~ /\\. { deny all; }`",
    validate: (body) => body.length > 50 && /\b(sudo|curl|wget|mysql|psql|ssh|scp|git|npm|docker|kubectl)\b/i.test(body),
  },

  // ── Database admin panels ─────────────────────────────────────────────────
  {
    path: "/phpmyadmin/",
    name: "phpMyAdmin Database Admin Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 8.1,
    category: "Information Disclosure",
    description: "A phpMyAdmin database administration interface is accessible. If default or weak credentials are used, attackers gain full database access including reading all data, exfiltrating user credentials, modifying records, and executing SQL to write webshells.",
    solution: "Restrict phpMyAdmin to localhost or VPN-only access. Enable authentication with a strong password. Ideally, remove it from the production server entirely and use a secure tunnel for DB access.",
    validate: (body) => /phpMyAdmin|phpmyadmin|pma_/i.test(body),
  },
  {
    path: "/adminer.php",
    name: "Adminer Database Admin Tool Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 8.1,
    category: "Information Disclosure",
    description: "Adminer (formerly phpMinAdmin) is publicly accessible. This single-file database admin tool gives attackers a GUI to connect to any database server visible from the web server, not just the local database.",
    solution: "Remove adminer.php from production immediately. For development use only — restrict with IP allowlisting if kept on staging servers.",
    validate: (body) => /adminer|Adminer/i.test(body),
  },

  // ── WordPress ─────────────────────────────────────────────────────────────
  {
    path: "/xmlrpc.php",
    name: "WordPress XML-RPC Enabled — Brute Force Amplification Vector",
    severity: "medium", cweId: "CWE-307", cvssScore: 7.5,
    category: "Brute Force Protection",
    description: "WordPress XML-RPC (xmlrpc.php) is accessible. The system.multicall method allows attackers to test thousands of username/password combinations in a single HTTP request, making brute-force attacks up to 1000× more efficient than targeting /wp-login.php directly. It's also used for DDoS amplification.",
    solution: "Disable XML-RPC if not needed (most sites don't need it): add `add_filter('xmlrpc_enabled', '__return_false');` to functions.php, or block it at the web server: `location = /xmlrpc.php { deny all; return 403; }`",
    validate: (body) => /xml version|xmlrpc|<methodResponse|<fault>/i.test(body),
  },

  // ── Spring Boot additional Actuator endpoints ─────────────────────────────
  {
    path: "/actuator/heapdump",
    name: "Spring Boot Heap Dump Endpoint Exposed — Full Memory Snapshot",
    severity: "critical", cweId: "CWE-200", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "The Spring Boot Actuator /heapdump endpoint is publicly accessible. This endpoint downloads a complete snapshot of the JVM heap memory, which contains ALL in-memory application data: database passwords, API keys, session tokens, decrypted secrets, user PII, and any other data the application has processed. An attacker can extract secrets directly from the heap dump using tools like Eclipse Memory Analyzer.",
    solution: "Restrict all Actuator endpoints immediately: `management.endpoints.web.exposure.include=health`. If heapdump is needed for debugging, restrict it to localhost or require authentication.",
    validate: (_, ct) => ct.includes("octet-stream") || ct.includes("x-java") || ct.includes("application/zip"),
  },
  {
    path: "/actuator/loggers",
    name: "Spring Boot Loggers Endpoint Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "The Spring Boot Actuator /loggers endpoint is accessible. Attackers can use this to increase log verbosity (e.g. enabling DEBUG) to extract sensitive data from logs, or to identify internal package structures.",
    solution: "Restrict Actuator endpoints to authenticated users or internal network only.",
    validate: (body) => /"loggers"|"levels"|"configuredLevel"/.test(body.slice(0, 1000)),
  },
  {
    path: "/actuator/metrics",
    name: "Spring Boot Metrics Endpoint Exposed",
    severity: "low", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "The Spring Boot Actuator /metrics endpoint reveals application performance counters, JVM statistics, and system resource usage. This aids attackers in understanding the application's technology stack and identifying attack windows.",
    solution: "Restrict all Actuator endpoints. Expose only /health publicly if needed.",
    validate: (body) => /"names"|"measurements"|"availableTags"/.test(body.slice(0, 1000)),
  },

  // ── Apache password / access control ─────────────────────────────────────
  {
    path: "/.htpasswd",
    name: "Apache .htpasswd Password File Exposed",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.1,
    category: "Credential Exposure",
    description: ".htpasswd is publicly accessible. This file contains usernames and hashed passwords used for HTTP Basic Authentication. The hashes (MD5-APR, bcrypt, SHA1) can be cracked offline with tools like hashcat or John the Ripper.",
    solution: "Remove .htpasswd from the web root. Configure Apache to block access to .ht* files (this is the default but can be accidentally overridden): `<Files ~ '^\\.ht'> Deny from all </Files>`",
    validate: (body) => /^[a-zA-Z0-9._-]+:\$apr1\$|^[a-zA-Z0-9._-]+:\{SHA\}|^[a-zA-Z0-9._-]+:[a-zA-Z0-9./]{13}/m.test(body),
  },

  // ── Apache / Nginx diagnostics ────────────────────────────────────────────
  {
    path: "/server-info",
    name: "Apache Server Info Page Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "Apache's /server-info page is accessible, revealing all loaded modules, configuration directives, virtual host settings, and compile-time options. This provides attackers a detailed map of the server configuration to find exploitable settings.",
    solution: "Disable mod_info or restrict to localhost: `<Location /server-info> Require local </Location>`",
    validate: (body) => /Apache Server Information|Server Settings|Module Name/i.test(body),
  },
  {
    path: "/nginx_status",
    name: "Nginx Status Page Exposed",
    severity: "low", cweId: "CWE-200",
    category: "Information Disclosure",
    description: "The Nginx stub_status page is accessible, showing active connections, total requests, and server state. While low severity on its own, it confirms the server is Nginx and reveals traffic patterns.",
    solution: "Restrict nginx_status to localhost: `allow 127.0.0.1; deny all;`",
    validate: (body) => /Active connections:|Reading:|Writing:|Waiting:|server accepts handled requests/i.test(body),
  },

  // ── Java / JEE ────────────────────────────────────────────────────────────
  {
    path: "/WEB-INF/web.xml",
    name: "Java Web Application Config (WEB-INF/web.xml) Exposed",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "The Java web application deployment descriptor (web.xml) is accessible. This file maps servlets, defines security constraints, lists initialization parameters, and may contain database JNDI references or other configuration that helps attackers understand the application structure.",
    solution: "Web servers should block direct access to WEB-INF by default. Verify your web server or servlet container is not misconfigured to serve this directory directly.",
    validate: (body) => /<web-app|<servlet|<filter|<context-param/i.test(body),
  },
  {
    path: "/WEB-INF/classes/application.properties",
    name: "Spring Application Properties Exposed (WEB-INF/classes/application.properties)",
    severity: "critical", cweId: "CWE-312", cvssScore: 9.8,
    category: "Credential Exposure",
    description: "The Spring Boot application.properties file is publicly accessible. This file contains datasource URLs with credentials, JWT secrets, API keys, mail server passwords, and all other application configuration.",
    solution: "Block the WEB-INF directory at your web server. Spring properties files must not be directly accessible from the web.",
    validate: (body) => /spring\.|datasource\.|server\.port|jwt\.|mail\.|security\./i.test(body),
  },

  // ── IDE configuration files ───────────────────────────────────────────────
  {
    path: "/.vscode/settings.json",
    name: "VS Code Workspace Settings Exposed",
    severity: "low", cweId: "CWE-200",
    category: "Information Disclosure",
    description: ".vscode/settings.json is accessible. While usually benign, editor settings can reveal database connection strings, local server addresses, plugin configurations, and file paths that help attackers understand the development environment.",
    solution: "Block .vscode at the web server. IDE config files should be in .gitignore and never deployed.",
    validate: (body, ct) => (ct.includes("json") || body.trim().startsWith("{")) && body.length > 20,
  },
  {
    path: "/.idea/workspace.xml",
    name: "JetBrains IDE Workspace Config Exposed",
    severity: "low", cweId: "CWE-200",
    category: "Information Disclosure",
    description: ".idea/workspace.xml contains JetBrains IDE workspace configuration, run configurations, data source settings (which may include database credentials), and local file paths.",
    solution: "Block the .idea directory at the web server. Add it to .gitignore.",
    validate: (body) => /<project|<component name=|<configuration/i.test(body),
  },

  // ── Generic config files ──────────────────────────────────────────────────
  {
    path: "/config.yaml",
    name: "YAML Configuration File Exposed (config.yaml)",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "A YAML configuration file is publicly accessible. YAML configs commonly contain database connection strings, API keys, service passwords, and internal endpoint URLs.",
    solution: "Remove config.yaml from the web root. Use environment variables for sensitive configuration.",
    validate: (body, ct) => (ct.includes("yaml") || /^[a-z_]+:/m.test(body)) && !ct.includes("text/html"),
  },
  {
    path: "/config.yml",
    name: "YAML Configuration File Exposed (config.yml)",
    severity: "high", cweId: "CWE-200", cvssScore: 7.5,
    category: "Information Disclosure",
    description: "A YAML configuration file is publicly accessible, potentially containing service credentials and infrastructure details.",
    solution: "Remove config.yml from the web root and use environment variables for sensitive values.",
    validate: (body, ct) => (ct.includes("yaml") || /^[a-z_]+:/m.test(body)) && !ct.includes("text/html"),
  },
  {
    path: "/app.yaml",
    name: "Google App Engine Configuration Exposed (app.yaml)",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "app.yaml is accessible. Google App Engine config files define runtime settings, environment variables, and service routing. Environment variable sections may contain API keys and credentials.",
    solution: "Block app.yaml at the web server. Use GCP Secret Manager for credentials.",
    validate: (body) => /runtime:|handlers:|env_variables:|service:|instance_class:/i.test(body),
  },

  // ── Additional API doc variants ────────────────────────────────────────────
  {
    path: "/api/swagger.json",
    name: "API Documentation Exposed (/api/swagger.json)",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "Swagger API documentation is exposed at /api/swagger.json, providing a full blueprint of API endpoints, parameters, authentication schemes, and data models.",
    solution: "Require authentication to access API documentation in production.",
    validate: (body) => /"swagger"|"openapi"/.test(body.slice(0, 500)),
  },
  {
    path: "/api/v1/swagger.json",
    name: "API v1 Documentation Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "API v1 Swagger documentation is publicly accessible, exposing the complete API surface for version 1.",
    solution: "Require authentication for API docs in production.",
    validate: (body) => /"swagger"|"openapi"/.test(body.slice(0, 500)),
  },
  {
    path: "/api/v2/swagger.json",
    name: "API v2 Documentation Exposed",
    severity: "medium", cweId: "CWE-200", cvssScore: 5.3,
    category: "Information Disclosure",
    description: "API v2 Swagger documentation is publicly accessible.",
    solution: "Require authentication for API docs in production.",
    validate: (body) => /"swagger"|"openapi"/.test(body.slice(0, 500)),
  },
];
